vich_uploader:
    db_driver: orm

    mappings:
        annonce_image:
            uri_prefix: /uploads/annonces
            upload_destination: '%kernel.project_dir%/public//uploads/annonces'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

